unsafe extern "C++" {
        include!("src/cpp/qt_widget.h");
// --- Qt opaque types ---
        type QApplication;
        type QWidget;
        type QPushButton;
        type QLabel;
        type QLineEdit;
        type QCheckBox;
        type QComboBox;
        type QTextEdit;
        type QSlider;
        type QProgressBar;
        type QTimer;
        type QVBoxLayout;
        type QHBoxLayout;
        type QGridLayout;
        type QLayout;
        type QRadioButton;
        type QGroupBox;
        type QTabWidget;
        type QSpinBox;
        type QMenu;
        type QMenuBar;
        type QIcon;
        type QPoint;
        type QListWidget;
        type QAction;
        type QMainWindow;
        type QToolBar;
        type QStatusBar;
        type QMessageBox;
        type QProgressDialog;
        type QTableWidget;
        type QTreeWidget;
        type QScrollArea;
        type QStackedWidget;
        type QSplitter;
        type QDateEdit;
        type QTimeEdit;
        type QDateTimeEdit;
        type QPlainTextEdit;
        type QTextBrowser;
        type QFrame;
        type QToolButton;
        type QCalendarWidget;
        type QShortcut;
        type QSystemTrayIcon;
        type QFont;
        type QUiLoader;
        type QDialog;
        type QFormLayout;
        type QDialogButtonBox;

        // --- Additional widget types ---
        type QDial;
        type QDoubleSpinBox;
        type QLCDNumber;
        type QScrollBar;
        type QDockWidget;
        type QToolBox;
        type QFontComboBox;
        type QButtonGroup;
        type QKeySequenceEdit;
        type QStringListModel;
        type QSortFilterProxyModel;
        type QCompleter;
        type QUndoStack;
        type QIntValidator;
        type QDoubleValidator;
        type QFileSystemModel;
        type QHeaderView;
        type QWizard;
        type QWizardPage;
        type QColumnView;
        type QAbstractButton;

        // --- Model/View types ---
        type QStandardItemModel;
        type QTableView;
        type QListView;
        type QTreeView;
        type QItemSelectionModel;
    }
